import Apartments from "@/components/apartments";
import UncontrolledExample from "@/components/carousel";
import Carousel from "@/components/carousel";
import "bootstrap/dist/css/bootstrap.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
export default function Home({ data }) {
  const[message,setMessage]=useState('');
  const[values,setValues]=useState({
    fullName:'',
    Email:'',
    phoneNo:'',
    purpose:'',
  })
  const{fullName,Email,phoneNo,purpose}=values;
  const handleChange=(e)=>{
    setValues({...values,[e.target.name]:e.target.value});

  }
  const handleSubmit=async(e)=>{
    e.preventDefault();
    const validRegex =
      /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
    if (!values.Email.match(validRegex)) {
      setMessage("invalid email please try again");
      return
    }
    try{
      const response=await fetch('/api/contact',{
        method:"POST",
        headers:{
            'Content-Type':'application/json',
        },
        body:JSON.stringify(values)
    })
    const data=await response.json();
    setMessage(data.message);
    setMessage('');
    setValues({
      Email:'',
      fullName:'',
      phoneNo:'',
      purpose:'',
    })
    }catch(err){
      console.log(err)
    }
  }
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="wrapper hero">
        <div className="hero__section">
          <div className="hero__carousel">
            <div className="hero__headline h3 py-3 ">
              Your Trustable Real Estate Agent & Property Manager in Budapest
            </div>
            <div>
              <UncontrolledExample />
            </div>
          </div>
          <div className="py-4 hero__video">
            <div>
              <video src="./crush.mp4" autoPlay muted loop></video>
            </div>
            <h2>Welcome to Empire SGN</h2>
            <p>
              When it comes to your property investment in Budapest, there is no
              other agency that understands you better than Empire real estate,
              with experience of hundreds of transactions and wide industry
              connections, we have everything you expect and require from a
              property investment, from locating your property, legal process,
              design & renovation, managing your property short or long-term
              rentals and until transferring the rent to you, all your property
              investment requirements under one roof.
            </p>
          </div>
        </div>
        <h1 className="display3 text-center">PROPERTY LISTING</h1>
        <div>
          <Apartments data={data} />
        </div>
        <div>
          <p className="text-center mt-2">
            <a className="display3 border border-success p-1 fw-bold" href="/">
              OUR SERVICES
            </a>
          </p>
          <div className="div">
            <div className="bg-secondary m-2 h-48 p-2">
              <h3>Real Estate Agency</h3>
              <p>
                A boutique real estate agency in Budapest for international &
                local investors focusing in Budapest properties, buying or
                selling, we are the first choice for our clients in their
                property investment
              </p>
            </div>
            <div className="bg-secondary m-2 h-48 p-2">
              <h3>Property Management</h3>
              <p>
                Put your mind at ease, trust us as your property managers and
                take all the hassle out of rent, monthly payments, maintenance,
                agents and tenant relations, let us be your property management
                in Budapest
              </p>
            </div>
            <div className="bg-secondary m-2 h-48 p-2">
              <h3>Design & Renovation</h3>
              <p>
                With our professional certified architects and visionary
                interior designers we can make your dream property come true,
                from a small to a large renovation, trust us to build your
                property in Budapest
              </p>
            </div>
          </div>
        </div>
        <div className="bg-white p-2">
          <form className="div2  mx-auto pe-2" onSubmit={handleSubmit}>
            <div className="form__image  me-3">
              <h1 className="text-left align-middle mt-5 text-danger h3">
                GET IN TOUCH
              </h1>
            </div>
            <div className="form__content mt-3">
              <div>
                <label htmlFor="fullname">fullname*</label>
                <br />
                <input
                  type="text"
                  id="fullname"
                  className="inp"
                  required
                  value={fullName}
                  name="fullName"
                  onChange={handleChange}
                />
              </div>
              <div>
                <label htmlFor="email">email*</label>
                <br />
                <input
                  
                  id="email"
                  className="inp"
                  value={Email}
                  required
                  name="Email"
                  onChange={handleChange}
                />
                <br />
              </div>
              <div>
                <label htmlFor="phone">phone no*</label>
                <br />
                <input
                  type="text"
                  id="phone"
                  className="inp"
                  required
                  value={phoneNo}
                  name="phoneNo"
                  onChange={handleChange}
                />
                <br />
              </div>
              <div>
                <label htmlFor="subject">subject*</label>
                <br />
                <select
                  id="subjcet"
                  placeholder="subject"
                  className="inp w-100"
                  name="purpose"
                  value={purpose}
                  onChange={handleChange}
                >
                  <option></option>
                  <option value="Buy Property">Buy Property</option>
                  <option value="Sell Property">Sell Property</option>
                  <option value="General Inquiries">General Inquiries</option>
                  <option value="Partener">Partener</option>
                </select>
              </div>
              <div>
                <button type='submit' className="my-2 btn btn-light">send</button>
              </div>
              <p>{message}</p>
            </div>
            
          </form>
        </div>
        <div className="market">
          <div className="text-center pt-2">
            <h1 className="mt-3">Budapest Property Market</h1>
            <h3>In Numbers</h3>
          </div>
          <div className="div">
            <div className="me-3 mb-5">
              <h2 className="text-center">15.5%</h2>
              <p className="text-center">
                Average annual property price growth in the last 7 years
              </p>
            </div>
            <div className="me-3 mb-5">
              <h2 className="text-center">6 -12%</h2>
              <p className="text-center">
                Budapest City average property rental annual yields
              </p>
            </div>
            <div className="mb-5">
              <h2 className="text-center">14mil +</h2>
              <p className="text-center">
                International visitors in Budapest City every year
              </p>
            </div>
          </div>
        </div>
        <div className="mt-3 d-md-flex justify-content-center ">
          {/* <div className="w-50 bg-primary me-3">
            <h1 className="text-center my-auto pt-5">SGN</h1>
          </div> */}
          <div className="w-75 mx-auto">
            <h3 className="text-center">OUR TEAM</h3>
            <p className="text-center">
              Imagine, your personal representative, running around, searching,
              analyzing, and negotiating with complete determination and
              persistence to achieve your goals, in order to get the most
              profitable deals for you. ​ So, stop imagining, and come to meet
              your team, highly motivated team of Carefully selected and
              professionally trained professionals, a team that knows how to
              understand what you are looking for, and how to find it for you.
            </p>
          </div>
        </div>
        <div className='team d-md-flex justify-content-center me-3'>
          <div className='mx-3'>
             <div className='team__image1'></div>
             <h3 className="text-center">Daniel Farkas</h3>
             <h5 className="text-center">Sales Manager</h5>
          </div>
          <div className='mx-3'>
             <div className='team__image2'></div>
             <h3 className="text-center">Krizstina Németh</h3>
             <h5 className="text-center">Property Management</h5>
          </div>
          <div className='mx-3'>
             <div className='team__image3'></div>
             <h3 className="text-center">Dora Kovács</h3>
             <h5 className="text-center">Investment Manager</h5>
          </div>
        </div>
        <div>
          <p className="text-center mt-4"><Link href='/' legacyBehavior><a className="h4 p-2 border border-success ">TESTIMONIALS</a></Link></p>
          <div className="d-md-flex justify-content-center">
            <div className="card m-2 p-3">
              <q>I turned to Empire to find a good property investment in Budapest, their approach was exactly what I was looking for, 
                I purchased a property through them and I am very satisfied</q>
                <p>Adrian Kögen</p>
            </div>
            <div className="card m-2 p-3">
              <q>After few bad experience with several local agents, I reached to Empire, 
                who really gave me all the attention, I almost lost my trust in the market, 
                but Empire professionally accompanied me to the end, 
                and still faithfully manages the property I purchased through them</q>
                <p>Oded Gazit</p>
            </div>
            <div className="card m-2 p-3">
              <q>Thank you for the kind service and patience in the face of my high demands, the excellent communication between us is worthy of note, I felt that you did your best to reach the result, and 
                I am happy that we reached a result that exceeded expectations</q>
                <p>Eva Lawsowski</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const { apartments } = await import("./Data/data.json");
  return {
    props: {
      data: apartments,
    },
  };
}
